jwtapp.front/Controllers/CategoryController.cs
using System.Text;
using System.Runtime.Serialization.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Text.Json;
using jwtapp.front.Models;

namespace jwtapp.front.Controllers
{

    [Authorize(Roles = "Admni")]    
    public class CategoryController : Controller
    {
        private readonly IHttpClientFactory _client;

        public CategoryController(IHttpClientFactory client)
        {
            _client = client;
        }

        public async Task<IActionResult> List()
        {
            var token = User.Claims.FirstOrDefault(x=>x.Type == "accessToken")?.Value;
            if (token != null)
            {
                var client = _client.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
                ("Bearer",token);
                var response = await client.GetAsync("https://localhost:7021/api/category");
                if (response.IsSuccessStatusCode)
                {
                    var jsondata = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<CategoryListModel>(jsondata,new JsonSerializerOptions{
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });
                    return View(result);
                }
            }
            return View();
                
            
        }
        public async Task<IActionResult> Remove(int id)
        {
            var token = User.Claims.FirstOrDefault(x=>x.Type == "accessToken")?.Value;
            if (token != null)
            {
                var client = _client.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
                ("Bearer",token);
                var response = await client.DeleteAsync($"https://localhost:7021/api/categories/{id}");
                
            }
            return RedirectToAction("List");
        }
        public IActionResult Create()
        {
            return View(new CreateCategoryModel());
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCategoryModel model)
        {
            if (ModelState.IsValid)
            {   
                var token = User.Claims.FirstOrDefault(x=>x.Type == "accessToken")?.Value;
            
                 if (token != null)
                 {
                    var client = _client.CreateClient();
                     client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
                    ("Bearer",token);
                    var jsonData = JsonSerializer.Serialize(model);
                    var content = new StringContent(jsonData,Encoding.UTF8,"application/json");
                    var response = await client.PostAsync("https://localhost:7021/api/categories/",content);
                    if (response.IsSuccessStatusCode)
                    {
                    return RedirectToAction("List");
                    }
                    else
                    {
                    ModelState.AddModelError("","Bir Hata Oluştu");
                    }
                }
            }     
            return View(model);
        }
        public async Task<IActionResult> Update(int id)
        {
            var token = User.Claims.FirstOrDefault(x=>x.Type == "accessToken")?.Value;
            if (token != null)
            {
                var client = _client.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
                ("Bearer",token);
                var response = await client.GetAsync($"https://localhost:7021/api/category/{id}");
                if (response.IsSuccessStatusCode)
                {
                    var jsondata = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<CategoryListModel>(jsondata,new JsonSerializerOptions{
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });
                    return View(result);  
                }
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Update(CategoryListModel model)
        {
                if (ModelState.IsValid)
            {   
                var token = User.Claims.FirstOrDefault(x=>x.Type == "accessToken")?.Value;
            
                 if (token != null)
                 {
                    var client = _client.CreateClient();
                     client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
                    ("Bearer",token);
                    var jsonData = JsonSerializer.Serialize(model);
                    var content = new StringContent(jsonData,Encoding.UTF8,"application/json");
                    var response = await client.PutAsync("https://localhost:7021/api/categories/",content);
                    if (response.IsSuccessStatusCode)
                    {
                    return RedirectToAction("List");
                    }
                    else
                    {
                    ModelState.AddModelError("","Bir Hata Oluştu");
                    }
                }
            }     
            return View(model);
        }
        
    }
}

jwtapp.front/Controllers/ProductController.cs
using System.Text;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using jwtapp.front.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace jwtapp.front.Controllers
{
   [Authorize(Roles ="Admin , Member")]
    public class ProductController : Controller
    {
        private readonly IHttpClientFactory _client;

        public ProductController(IHttpClientFactory client)
        {
            _client = client;
        }
        public async Task<IActionResult> List()
        {
            var token = User.Claims.FirstOrDefault(x=>x.Type == "accessToken")?.Value;
            if (token != null)
            {
                var client = _client.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
                ("Bearer",token);
                var response = await client.GetAsync("https://localhost:7021/api/product");
                if (response.IsSuccessStatusCode)
                {
                    var jsondata = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<ProductListModel>(jsondata,new JsonSerializerOptions{
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });
                    return View(result);
                }
            }
            return View();
                
            
        }
        public async Task<IActionResult> Remove(int id)
        {
            var token = User.Claims.FirstOrDefault(x=>x.Type == "accessToken")?.Value;
            if (token != null)
            {
                var client = _client.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
                ("Bearer",token);
                 await client.DeleteAsync($"https://localhost:7021/api/product/{id}");
                
            }
            return RedirectToAction("List");
        }
        public async Task<IActionResult> Create()
        {
                var token = User.Claims.FirstOrDefault(x=>x.Type == "accessToken")?.Value;
                if (token != null)
                {
                    var client = _client.CreateClient();
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
                    ("Bearer",token);
                    var response = await client.GetAsync("https://localhost:7021/api/category");
                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var data = JsonSerializer.Deserialize<List<CategoryListModel>>(jsonData,new JsonSerializerOptions{
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });
                var model = new CreateProductModel()
                {
                    Categories = new SelectList(data,"Id","Definition")
                };
                return View(model);
                }
                               
            }
           
            return RedirectToAction("List");
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateProductModel model)
        {
            var data = TempData["Categories"]?.ToString();
            if (data != null)
            {
                var categories = JsonSerializer.Deserialize<List<SelectListItem>>(data);
                model.Categories = new SelectList(categories,"Value","Text");
            }
            if (ModelState.IsValid)
            {
                var token = User.Claims.FirstOrDefault(x=>x.Type == "accessToken")?.Value;
                if (token != null)
                {
                    var client = _client.CreateClient();
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
                    ("Bearer",token);

                    var jsonData = JsonSerializer.Serialize(model);
                    var content = new StringContent(jsonData, Encoding.UTF8,"application/json");


                    var response = await client.PostAsync("https://localhost:7021/api/product",content);
                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("List");
                    }
                    ModelState.AddModelError("","Bir Hata Oluştu");
                }
                
            }
            return View(model);
        }

        public async Task<IActionResult> Update(int id)
        {
            var token = User.Claims.FirstOrDefault(x=>x.Type == "accessToken")?.Value;
            if (token != null)
            {
                var client = _client.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
                ("Bearer",token);
                
                var responseCategory = await client.GetAsync("https://localhost:7021/api/category");
                if (responseCategory.IsSuccessStatusCode)
                {
                     var jsonData = await responseCategory.Content.ReadAsStringAsync();
                    var data = JsonSerializer.Deserialize<List<CategoryListModel>>(jsonData,new JsonSerializerOptions{
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });
                var model = new CreateProductModel()
                {
                    Categories = new SelectList(data,"Id","Definition")
                };
                }
                
                var responseProduct = await client.GetAsync($"https://localhost:7021/api/product/{id}");
                if (responseProduct.IsSuccessStatusCode)
                {
                    var jsondata = await responseProduct.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<UpdateProductModel>(jsondata,new JsonSerializerOptions{
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });
                    return View(result);  
                }
            }
            return View();
        }
    }
}

jwtapp.front/Views/Product/Create.cshtml
@using System.Text.Json
@model CreateProductModel
@{
    Layout="_Layout";
}
<div>
    <form class="w-75 m-5 p-3" method="post" asp-action="Create" asp-controller="Category">
        @{
            TempData["Categories"] = JsonSerializer.Serialize(Model.Categories);
        }
        <div class="mb-3">
            <label for="@Model.Name">Ürün Adi Giriniz</label>
            <input type="text" asp-for="@Model.Name" class="form-control">
            <span class="text-danger" asp-validation-for="@Model.Name"></span>
        </div>
        <div class="mb-3">
            <label for="@Model.Price">Ürün Fiyati Giriniz</label>
            <input type="text" asp-for="@Model.Price" class="form-control">
            <span class="text-danger" asp-validation-for="@Model.Price"></span>
        </div>
        <div class="mb-3">
            <label for="@Model.Stock">Ürün Stock Giriniz</label>
            <input type="text" asp-for="@Model.Stock" class="form-control">
            <span class="text-danger" asp-validation-for="@Model.Stock"></span>
        </div>
        <div class="mb-3">
            <label for="@Model.CategoryId">Kategori Giriniz</label>
            <select class="form-select" asp-items="@Model.Categories" asp-for="@Model.CategoryId">
                <option selected>Kategori Seçiniz</option>
            </select>
        </div>
        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Ekle</button>
        </div>
    </form>
</div>

jwtapp.front/Views/Product/List.cshtml
@model List<ProductListModel>
@{
    Layout="_Layout";
}   
@if(Model.Count > 0)
{
<h2>Kategori Listesi</h2>
<div class="text-end">
    <a asp-action="Create" asp-controller="Category">Yeni Kategori Oluştur</a>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Ürün</th>
      <th scope="col">Stok</th>
      <th scope="col">Fiyat</th>
      <th scope="col">İşlemler</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var product in Model)
    {
    <tr>
      <th scope="row">@product.Id</th>
      <td>@product.Name</td>
      <td>@product.Stock</td>
      <td>@product.Price</td>
      <td>
        <a class="btn btn-danger" asp-action="Remove" asp-controller="Product" asp-route-id="@product.Id">Sil</a>
        <a class="btn btn-danger" asp-action="Update" asp-controller="Product" asp-route-id="@product.Id">Güncelle</a>
      </td>
    </tr>    
    }
    
  </tbody>
</table>
}
else
{


}

jwtapp.front/Views/Product/Product.cshtml
@model UpdateProductModel
@{
    Layout="_Layout";
}
<div>
    <form class="w-75 m-5 p-3" method="post" asp-action="Update" asp-controller="Category">
        <input type="hidden" asp-for="@Model.Id">
        <div class="mb-3">
            <label for="@Model.Definition">Kategori Adı</label>
            <span class="text-danger" asp-validation-for="@Model.Definition"></span>
            <input type="text" asp-for="@Model.Definition" class="form-control">
        </div>
        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Güncelle</button>
        </div>
    </form>
</div>